# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('title', 'pub_date')),
        ),
    ]
