# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160503_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytopost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorytopost',
            name='post',
        ),
        migrations.DeleteModel(
            name='CategoryToPost',
        ),
    ]
