# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20160503_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='creator',
        ),
    ]
