# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160503_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='author',
        ),
    ]
