# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160422_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteMeta',
            new_name='SiteMetaSeo',
        ),
    ]
