# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_proramminglanguges_skills_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProrammingLanguges',
            new_name='ProgrammingLanguge',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
