# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160422_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguge',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.AddField(
            model_name='programminglanguge',
            name='image',
            field=models.ImageField(null='true', upload_to='images'),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(null='true', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='headercover',
            name='image',
            field=models.ImageField(null='true', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='sitemetaseo',
            name='image',
            field=models.ImageField(null='true', upload_to='images'),
        ),
    ]
