# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20160424_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontcover',
            name='image',
            field=models.ImageField(null='true', upload_to='images'),
        ),
    ]
