# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_frontcover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
