# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
