# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20160425_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True, verbose_name='Add Address and Contacts')),
                ('objective', models.TextField(null=True, verbose_name='Add you objectives')),
                ('experience', models.TextField(null=True, verbose_name='Add your experiences')),
                ('seminar', models.TextField(null=True, verbose_name='Add your seminar attendies')),
                ('education', models.TextField(null=True, verbose_name='Add you educational background')),
                ('personal_data', models.TextField(null=True, verbose_name='Add you personal data')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
