# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='education',
        ),
        migrations.RemoveField(
            model_name='about',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='about',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='about',
            name='personal_data',
        ),
        migrations.RemoveField(
            model_name='about',
            name='seminar',
        ),
    ]
