# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20160503_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
