# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20160503_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
