# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 09:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_about_about_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
